
services:
  springbootapp:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresDB:5432/todoapi
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
  db:
    container_name: postgresDB
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todoapi
    ports:
      - 5432:5432

volumes:
  postgres_data:
